<?php

namespace Database\Seeders;

use App\Models\District;
use App\Models\State;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            [ "state" => "Andaman and Nicobar Islands", "name"  =>  "NICOBARS", ],
            [ "state" => "Andaman and Nicobar Islands", "name"  =>  "NORTH AND MIDDLE ANDAMAN", ],
            [ "state" => "Andaman and Nicobar Islands", "name"  =>  "SOUTH ANDAMANS", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Alluri Sitharama Raju", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Anakapalli", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "ANANTAPUR", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Annamayya", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Bapatla", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "CHITTOOR", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "EAST GODAVARI", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Eluru", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "GUNTUR", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Kakinada", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Konaseema", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "KRISHNA", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "KURNOOL", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Nandyal", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "NTR", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Palnadu", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Parvathipuram Manyam", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "PRAKASAM", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "SPSR NELLORE", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "SRIKAKULAM", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Sri Sathya Sai", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Tirupati", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "VISAKHAPATANAM", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "VIZIANAGARAM", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "WEST GODAVARI", ],
            [ "state" => "Andhra Pradesh",              "name"  =>  "Y.S.R.", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "ANJAW", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "CHANGLANG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "DIBANG VALLEY", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "EAST KAMENG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "EAST SIANG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "KAMLE", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "KRA DAADI", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "KURUNG KUMEY", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "LEPARADA", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "LOHIT", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "LONGDING", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "LOWER DIBANG VALLEY", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "LOWER SIANG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "LOWER SUBANSIRI", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "NAMSAI", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "PAKKE KESSANG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "PAPUM PARE", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "SHI YOMI", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "SIANG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "TAWANG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "TIRAP", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "UPPER SIANG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "UPPER SUBANSIRI", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "WEST KAMENG", ],
            [ "state" => "Arunachal Pradesh",           "name"  =>  "WEST SIANG", ],
            [ "state" => "Assam",                         "name"  =>  "BAJALI", ],
            [ "state" => "Assam",                         "name"  =>  "BAKSA", ],
            [ "state" => "Assam",                         "name"  =>  "BARPETA", ],
            [ "state" => "Assam",                         "name"  =>  "Biswanath", ],
            [ "state" => "Assam",                         "name"  =>  "BONGAIGAON", ],
            [ "state" => "Assam",                         "name"  =>  "CACHAR", ],
            [ "state" => "Assam",                         "name"  =>  "CHARAIDEO", ],
            [ "state" => "Assam",                         "name"  =>  "CHIRANG", ],
            [ "state" => "Assam",                         "name"  =>  "DARRANG", ],
            [ "state" => "Assam",                         "name"  =>  "DHEMAJI", ],
            [ "state" => "Assam",                         "name"  =>  "DHUBRI", ],
            [ "state" => "Assam",                         "name"  =>  "DIBRUGARH", ],
            [ "state" => "Assam",                         "name"  =>  "DIMA HASAO", ],
            [ "state" => "Assam",                         "name"  =>  "GOALPARA", ],
            [ "state" => "Assam",                         "name"  =>  "GOLAGHAT", ],
            [ "state" => "Assam",                         "name"  =>  "HAILAKANDI", ],
            [ "state" => "Assam",                         "name"  =>  "HOJAI", ],
            [ "state" => "Assam",                         "name"  =>  "JORHAT", ],
            [ "state" => "Assam",                         "name"  =>  "KAMRUP", ],
            [ "state" => "Assam",                         "name"  =>  "KAMRUP METRO", ],
            [ "state" => "Assam",                         "name"  =>  "KARBI ANGLONG", ],
            [ "state" => "Assam",                         "name"  =>  "KARIMGANJ", ],
            [ "state" => "Assam",                         "name"  =>  "KOKRAJHAR", ],
            [ "state" => "Assam",                         "name"  =>  "LAKHIMPUR", ],
            [ "state" => "Assam",                         "name"  =>  "MAJULI", ],
            [ "state" => "Assam",                         "name"  =>  "MARIGAON", ],
            [ "state" => "Assam",                         "name"  =>  "NAGAON", ],
            [ "state" => "Assam",                         "name"  =>  "NALBARI", ],
            [ "state" => "Assam",                         "name"  =>  "SIVASAGAR", ],
            [ "state" => "Assam",                         "name"  =>  "SONITPUR", ],
            [ "state" => "Assam",                         "name"  =>  "SOUTH SALMARA MANCACHAR", ],
            [ "state" => "Assam",                         "name"  =>  "TAMULPUR", ],
            [ "state" => "Assam",                         "name"  =>  "TINSUKIA", ],
            [ "state" => "Assam",                         "name"  =>  "UDALGURI", ],
            [ "state" => "Assam",                         "name"  =>  "WEST KARBI ANGLONG", ],
            [ "state" => "Bihar",                         "name"  =>  "ARARIA", ],
            [ "state" => "Bihar",                         "name"  =>  "ARWAL", ],
            [ "state" => "Bihar",                         "name"  =>  "AURANGABAD", ],
            [ "state" => "Bihar",                         "name"  =>  "BANKA", ],
            [ "state" => "Bihar",                         "name"  =>  "BEGUSARAI", ],
            [ "state" => "Bihar",                         "name"  =>  "BHAGALPUR", ],
            [ "state" => "Bihar",                         "name"  =>  "BHOJPUR", ],
            [ "state" => "Bihar",                         "name"  =>  "BUXAR", ],
            [ "state" => "Bihar",                         "name"  =>  "DARBHANGA", ],
            [ "state" => "Bihar",                         "name"  =>  "GAYA", ],
            [ "state" => "Bihar",                         "name"  =>  "GOPALGANJ", ],
            [ "state" => "Bihar",                         "name"  =>  "JAMUI", ],
            [ "state" => "Bihar",                         "name"  =>  "JEHANABAD", ],
            [ "state" => "Bihar",                         "name"  =>  "KAIMUR (BHABUA)", ],
            [ "state" => "Bihar",                         "name"  =>  "KATIHAR", ],
            [ "state" => "Bihar",                         "name"  =>  "KHAGARIA", ],
            [ "state" => "Bihar",                         "name"  =>  "KISHANGANJ", ],
            [ "state" => "Bihar",                         "name"  =>  "LAKHISARAI", ],
            [ "state" => "Bihar",                         "name"  =>  "MADHEPURA", ],
            [ "state" => "Bihar",                         "name"  =>  "MADHUBANI", ],
            [ "state" => "Bihar",                         "name"  =>  "MUNGER", ],
            [ "state" => "Bihar",                         "name"  =>  "MUZAFFARPUR", ],
            [ "state" => "Bihar",                         "name"  =>  "NALANDA", ],
            [ "state" => "Bihar",                         "name"  =>  "NAWADA", ],
            [ "state" => "Bihar",                         "name"  =>  "PASHCHIM CHAMPARAN", ],
            [ "state" => "Bihar",                         "name"  =>  "PATNA", ],
            [ "state" => "Bihar",                         "name"  =>  "PURBI CHAMPARAN", ],
            [ "state" => "Bihar",                         "name"  =>  "PURNIA", ],
            [ "state" => "Bihar",                         "name"  =>  "ROHTAS", ],
            [ "state" => "Bihar",                         "name"  =>  "SAHARSA", ],
            [ "state" => "Bihar",                         "name"  =>  "SAMASTIPUR", ],
            [ "state" => "Bihar",                         "name"  =>  "SARAN", ],
            [ "state" => "Bihar",                         "name"  =>  "SHEIKHPURA", ],
            [ "state" => "Bihar",                         "name"  =>  "SHEOHAR", ],
            [ "state" => "Bihar",                         "name"  =>  "SITAMARHI", ],
            [ "state" => "Bihar",                         "name"  =>  "SIWAN", ],
            [ "state" => "Bihar",                         "name"  =>  "SUPAUL", ],
            [ "state" => "Bihar",                         "name"  =>  "VAISHALI", ],
            [ "state" => "Chandigarh",                    "name"  =>  "CHANDIGARH", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "BALOD", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "BALODA BAZAR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "BALRAMPUR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "BASTAR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "BEMETARA", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "BIJAPUR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "BILASPUR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "DANTEWADA", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "DHAMTARI", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "DURG", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "GARIYABAND", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "Gaurella Pendra Marwahi", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "JANJGIR-CHAMPA", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "JASHPUR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "KABIRDHAM", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "KANKER", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "KHAIRGARH CHHUIKHADAN GANDAI", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "KONDAGAON", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "KORBA", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "KOREA", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "MAHASAMUND", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "MANENDRAGARH CHIRIMIRI BHARATPUR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "MOHLA MANPUR AMBAGARH CHOUKI", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "MUNGELI", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "NARAYANPUR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "RAIGARH", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "RAIPUR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "RAJNANDGAON", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "SAKTI", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "SARANGARH BILAIGARH", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "SUKMA", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "SURAJPUR", ],
            [ "state" => "Chhattisgarh",                  "name"  =>  "SURGUJA", ],
            [ "state" => "Delhi",                         "name"  =>  "CENTRAL", ],
            [ "state" => "Delhi",                         "name"  =>  "EAST", ],
            [ "state" => "Delhi",                         "name"  =>  "NEW DELHI", ],
            [ "state" => "Delhi",                         "name"  =>  "NORTH", ],
            [ "state" => "Delhi",                         "name"  =>  "NORTH EAST", ],
            [ "state" => "Delhi",                         "name"  =>  "NORTH WEST", ],
            [ "state" => "Delhi",                         "name"  =>  "SHAHDARA", ],
            [ "state" => "Delhi",                         "name"  =>  "SOUTH", ],
            [ "state" => "Delhi",                         "name"  =>  "South East", ],
            [ "state" => "Delhi",                         "name"  =>  "SOUTH WEST", ],
            [ "state" => "Delhi",                         "name"  =>  "WEST", ],
            [ "state" => "Goa",                           "name"  =>  "NORTH GOA", ],
            [ "state" => "Goa",                           "name"  =>  "SOUTH GOA", ],
            [ "state" => "Gujarat",                       "name"  =>  "AHMADABAD", ],
            [ "state" => "Gujarat",                       "name"  =>  "AMRELI", ],
            [ "state" => "Gujarat",                       "name"  =>  "ANAND", ],
            [ "state" => "Gujarat",                       "name"  =>  "ARVALLI", ],
            [ "state" => "Gujarat",                       "name"  =>  "BANAS KANTHA", ],
            [ "state" => "Gujarat",                       "name"  =>  "BHARUCH", ],
            [ "state" => "Gujarat",                       "name"  =>  "BHAVNAGAR", ],
            [ "state" => "Gujarat",                       "name"  =>  "BOTAD", ],
            [ "state" => "Gujarat",                       "name"  =>  "CHHOTAUDEPUR", ],
            [ "state" => "Gujarat",                       "name"  =>  "DANG", ],
            [ "state" => "Gujarat",                       "name"  =>  "DEVBHUMI DWARKA", ],
            [ "state" => "Gujarat",                       "name"  =>  "DOHAD", ],
            [ "state" => "Gujarat",                       "name"  =>  "GANDHINAGAR", ],
            [ "state" => "Gujarat",                       "name"  =>  "GIR SOMNATH", ],
            [ "state" => "Gujarat",                       "name"  =>  "JAMNAGAR", ],
            [ "state" => "Gujarat",                       "name"  =>  "JUNAGADH", ],
            [ "state" => "Gujarat",                       "name"  =>  "KACHCHH", ],
            [ "state" => "Gujarat",                       "name"  =>  "KHEDA", ],
            [ "state" => "Gujarat",                       "name"  =>  "MAHESANA", ],
            [ "state" => "Gujarat",                       "name"  =>  "Mahisagar", ],
            [ "state" => "Gujarat",                       "name"  =>  "MORBI", ],
            [ "state" => "Gujarat",                       "name"  =>  "NARMADA", ],
            [ "state" => "Gujarat",                       "name"  =>  "NAVSARI", ],
            [ "state" => "Gujarat",                       "name"  =>  "PANCH MAHALS", ],
            [ "state" => "Gujarat",                       "name"  =>  "PATAN", ],
            [ "state" => "Gujarat",                       "name"  =>  "PORBANDAR", ],
            [ "state" => "Gujarat",                       "name"  =>  "RAJKOT", ],
            [ "state" => "Gujarat",                       "name"  =>  "SABAR KANTHA", ],
            [ "state" => "Gujarat",                       "name"  =>  "SURAT", ],
            [ "state" => "Gujarat",                       "name"  =>  "SURENDRANAGAR", ],
            [ "state" => "Gujarat",                       "name"  =>  "TAPI", ],
            [ "state" => "Gujarat",                       "name"  =>  "VADODARA", ],
            [ "state" => "Gujarat",                       "name"  =>  "VALSAD", ],
            [ "state" => "Haryana",                       "name"  =>  "AMBALA", ],
            [ "state" => "Haryana",                       "name"  =>  "BHIWANI", ],
            [ "state" => "Haryana",                       "name"  =>  "CHARKI DADRI", ],
            [ "state" => "Haryana",                       "name"  =>  "FARIDABAD", ],
            [ "state" => "Haryana",                       "name"  =>  "FATEHABAD", ],
            [ "state" => "Haryana",                       "name"  =>  "GURUGRAM", ],
            [ "state" => "Haryana",                       "name"  =>  "HISAR", ],
            [ "state" => "Haryana",                       "name"  =>  "JHAJJAR", ],
            [ "state" => "Haryana",                       "name"  =>  "JIND", ],
            [ "state" => "Haryana",                       "name"  =>  "KAITHAL", ],
            [ "state" => "Haryana",                       "name"  =>  "KARNAL", ],
            [ "state" => "Haryana",                       "name"  =>  "KURUKSHETRA", ],
            [ "state" => "Haryana",                       "name"  =>  "MAHENDRAGARH", ],
            [ "state" => "Haryana",                       "name"  =>  "NUH", ],
            [ "state" => "Haryana",                       "name"  =>  "PALWAL", ],
            [ "state" => "Haryana",                       "name"  =>  "PANCHKULA", ],
            [ "state" => "Haryana",                       "name"  =>  "PANIPAT", ],
            [ "state" => "Haryana",                       "name"  =>  "REWARI", ],
            [ "state" => "Haryana",                       "name"  =>  "ROHTAK", ],
            [ "state" => "Haryana",                       "name"  =>  "SIRSA", ],
            [ "state" => "Haryana",                       "name"  =>  "SONIPAT", ],
            [ "state" => "Haryana",                       "name"  =>  "YAMUNANAGAR", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "BILASPUR", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "CHAMBA", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "HAMIRPUR", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "KANGRA", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "KINNAUR", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "KULLU", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "LAHUL AND SPITI", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "MANDI", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "SHIMLA", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "SIRMAUR", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "SOLAN", ],
            [ "state" => "Himachal Pradesh",            "name"  =>  "UNA", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "ANANTNAG", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "BANDIPORA", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "BARAMULLA", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "Budgam", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "DODA", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "GANDERBAL", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "JAMMU", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "KATHUA", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "KISHTWAR", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "KULGAM", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "KUPWARA", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "POONCH", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "PULWAMA", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "RAJOURI", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "RAMBAN", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "REASI", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "SAMBA", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "SHOPIAN", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "SRINAGAR", ],
            [ "state" => "Jammu and Kashmir",           "name"  =>  "UDHAMPUR", ],
            [ "state" => "Jharkhand",                     "name"  =>  "BOKARO", ],
            [ "state" => "Jharkhand",                     "name"  =>  "CHATRA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "DEOGHAR", ],
            [ "state" => "Jharkhand",                     "name"  =>  "DHANBAD", ],
            [ "state" => "Jharkhand",                     "name"  =>  "DUMKA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "EAST SINGHBUM", ],
            [ "state" => "Jharkhand",                     "name"  =>  "GARHWA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "GIRIDIH", ],
            [ "state" => "Jharkhand",                     "name"  =>  "GODDA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "GUMLA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "HAZARIBAGH", ],
            [ "state" => "Jharkhand",                     "name"  =>  "JAMTARA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "KHUNTI", ],
            [ "state" => "Jharkhand",                     "name"  =>  "KODERMA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "LATEHAR", ],
            [ "state" => "Jharkhand",                     "name"  =>  "LOHARDAGA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "PAKUR", ],
            [ "state" => "Jharkhand",                     "name"  =>  "PALAMU", ],
            [ "state" => "Jharkhand",                     "name"  =>  "RAMGARH", ],
            [ "state" => "Jharkhand",                     "name"  =>  "RANCHI", ],
            [ "state" => "Jharkhand",                     "name"  =>  "SAHEBGANJ", ],
            [ "state" => "Jharkhand",                     "name"  =>  "SARAIKELA KHARSAWAN", ],
            [ "state" => "Jharkhand",                     "name"  =>  "SIMDEGA", ],
            [ "state" => "Jharkhand",                     "name"  =>  "WEST SINGHBHUM", ],
            [ "state" => "Karnataka",                     "name"  =>  "BAGALKOTE", ],
            [ "state" => "Karnataka",                     "name"  =>  "BALLARI", ],
            [ "state" => "Karnataka",                     "name"  =>  "BELAGAVI", ],
            [ "state" => "Karnataka",                     "name"  =>  "BENGALURU RURAL", ],
            [ "state" => "Karnataka",                     "name"  =>  "BENGALURU URBAN", ],
            [ "state" => "Karnataka",                     "name"  =>  "BIDAR", ],
            [ "state" => "Karnataka",                     "name"  =>  "CHAMARAJANAGARA", ],
            [ "state" => "Karnataka",                     "name"  =>  "CHIKKABALLAPURA", ],
            [ "state" => "Karnataka",                     "name"  =>  "CHIKKAMAGALURU", ],
            [ "state" => "Karnataka",                     "name"  =>  "CHITRADURGA", ],
            [ "state" => "Karnataka",                     "name"  =>  "DAKSHINA KANNADA", ],
            [ "state" => "Karnataka",                     "name"  =>  "DAVANGERE", ],
            [ "state" => "Karnataka",                     "name"  =>  "DHARWAD", ],
            [ "state" => "Karnataka",                     "name"  =>  "GADAG", ],
            [ "state" => "Karnataka",                     "name"  =>  "HASSAN", ],
            [ "state" => "Karnataka",                     "name"  =>  "HAVERI", ],
            [ "state" => "Karnataka",                     "name"  =>  "KALABURAGI", ],
            [ "state" => "Karnataka",                     "name"  =>  "KODAGU", ],
            [ "state" => "Karnataka",                     "name"  =>  "KOLAR", ],
            [ "state" => "Karnataka",                     "name"  =>  "KOPPAL", ],
            [ "state" => "Karnataka",                     "name"  =>  "MANDYA", ],
            [ "state" => "Karnataka",                     "name"  =>  "MYSURU", ],
            [ "state" => "Karnataka",                     "name"  =>  "RAICHUR", ],
            [ "state" => "Karnataka",                     "name"  =>  "RAMANAGARA", ],
            [ "state" => "Karnataka",                     "name"  =>  "SHIVAMOGGA", ],
            [ "state" => "Karnataka",                     "name"  =>  "TUMAKURU", ],
            [ "state" => "Karnataka",                     "name"  =>  "UDUPI", ],
            [ "state" => "Karnataka",                     "name"  =>  "UTTARA KANNADA", ],
            [ "state" => "Karnataka",                     "name"  =>  "VIJAYANAGAR", ],
            [ "state" => "Karnataka",                     "name"  =>  "VIJAYAPURA", ],
            [ "state" => "Karnataka",                     "name"  =>  "YADGIR", ],
            [ "state" => "Kerala",                        "name"  =>  "ALAPPUZHA", ],
            [ "state" => "Kerala",                        "name"  =>  "ERNAKULAM", ],
            [ "state" => "Kerala",                        "name"  =>  "IDUKKI", ],
            [ "state" => "Kerala",                        "name"  =>  "KANNUR", ],
            [ "state" => "Kerala",                        "name"  =>  "KASARAGOD", ],
            [ "state" => "Kerala",                        "name"  =>  "KOLLAM", ],
            [ "state" => "Kerala",                        "name"  =>  "KOTTAYAM", ],
            [ "state" => "Kerala",                        "name"  =>  "KOZHIKODE", ],
            [ "state" => "Kerala",                        "name"  =>  "MALAPPURAM", ],
            [ "state" => "Kerala",                        "name"  =>  "PALAKKAD", ],
            [ "state" => "Kerala",                        "name"  =>  "PATHANAMTHITTA", ],
            [ "state" => "Kerala",                        "name"  =>  "THIRUVANANTHAPURAM", ],
            [ "state" => "Kerala",                        "name"  =>  "THRISSUR", ],
            [ "state" => "Kerala",                        "name"  =>  "WAYANAD", ],
            [ "state" => "Ladakh",                        "name"  =>  "KARGIL", ],
            [ "state" => "Ladakh",                        "name"  =>  "LEH LADAKH", ],
            [ "state" => "Lakshadweep",                   "name"  =>  "LAKSHADWEEP DISTRICT", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "AGAR MALWA" ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "ALIRAJPUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "ANUPPUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "ASHOKNAGAR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "BALAGHAT", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "BARWANI", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "BETUL", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "BHIND", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "BHOPAL", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "BURHANPUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "CHHATARPUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "CHHINDWARA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "DAMOH", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "DATIA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "DEWAS", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "DHAR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "DINDORI", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "EAST NIMAR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "GUNA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "GWALIOR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "HARDA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "INDORE", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "JABALPUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "JHABUA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "KATNI", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "KHARGONE", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "MANDLA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "MANDSAUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "MORENA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "NARMADAPURAM", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "NARSINGHPUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "NEEMUCH", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "Niwari", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "PANNA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "RAISEN", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "RAJGARH", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "RATLAM", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "REWA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SAGAR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SATNA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SEHORE", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SEONI", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SHAHDOL", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SHAJAPUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SHEOPUR", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SHIVPURI", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SIDHI", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "SINGRAULI", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "TIKAMGARH", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "UJJAIN", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "UMARIA", ],
            [ "state" => "Madhya Pradesh",             "name"  =>  "VIDISHA", ],
            [ "state" => "Maharashtra",                 "name"  =>  "AHMEDNAGAR", ],
            [ "state" => "Maharashtra",                 "name"  =>  "AKOLA", ],
            [ "state" => "Maharashtra",                 "name"  =>  "AMRAVATI", ],
            [ "state" => "Maharashtra",                 "name"  =>  "AURANGABAD", ],
            [ "state" => "Maharashtra",                 "name"  =>  "BEED", ],
            [ "state" => "Maharashtra",                 "name"  =>  "BHANDARA", ],
            [ "state" => "Maharashtra",                 "name"  =>  "BULDHANA", ],
            [ "state" => "Maharashtra",                 "name"  =>  "CHANDRAPUR", ],
            [ "state" => "Maharashtra",                 "name"  =>  "DHULE", ],
            [ "state" => "Maharashtra",                 "name"  =>  "GADCHIROLI", ],
            [ "state" => "Maharashtra",                 "name"  =>  "GONDIA", ],
            [ "state" => "Maharashtra",                 "name"  =>  "HINGOLI", ],
            [ "state" => "Maharashtra",                 "name"  =>  "JALGAON", ],
            [ "state" => "Maharashtra",                 "name"  =>  "JALNA", ],
            [ "state" => "Maharashtra",                 "name"  =>  "KOLHAPUR", ],
            [ "state" => "Maharashtra",                 "name"  =>  "LATUR", ],
            [ "state" => "Maharashtra",                 "name"  =>  "MUMBAI", ],
            [ "state" => "Maharashtra",                 "name"  =>  "MUMBAI SUBURBAN", ],
            [ "state" => "Maharashtra",                 "name"  =>  "NAGPUR", ],
            [ "state" => "Maharashtra",                 "name"  =>  "NANDED", ],
            [ "state" => "Maharashtra",                 "name"  =>  "NANDURBAR", ],
            [ "state" => "Maharashtra",                 "name"  =>  "NASHIK", ],
            [ "state" => "Maharashtra",                 "name"  =>  "OSMANABAD", ],
            [ "state" => "Maharashtra",                 "name"  =>  "PALGHAR", ],
            [ "state" => "Maharashtra",                 "name"  =>  "PARBHANI", ],
            [ "state" => "Maharashtra",                 "name"  =>  "PUNE", ],
            [ "state" => "Maharashtra",                 "name"  =>  "RAIGAD", ],
            [ "state" => "Maharashtra",                 "name"  =>  "RATNAGIRI", ],
            [ "state" => "Maharashtra",                 "name"  =>  "SANGLI", ],
            [ "state" => "Maharashtra",                 "name"  =>  "SATARA", ],
            [ "state" => "Maharashtra",                 "name"  =>  "SINDHUDURG", ],
            [ "state" => "Maharashtra",                 "name"  =>  "SOLAPUR", ],
            [ "state" => "Maharashtra",                 "name"  =>  "THANE", ],
            [ "state" => "Maharashtra",                 "name"  =>  "WARDHA", ],
            [ "state" => "Maharashtra",                 "name"  =>  "WASHIM", ],
            [ "state" => "Maharashtra",                 "name"  =>  "YAVATMAL", ],
            [ "state" => "Manipur",                     "name"  =>  "BISHNUPUR", ],
            [ "state" => "Manipur",                     "name"  =>  "CHANDEL", ],
            [ "state" => "Manipur",                     "name"  =>  "CHURACHANDPUR", ],
            [ "state" => "Manipur",                     "name"  =>  "IMPHAL EAST", ],
            [ "state" => "Manipur",                     "name"  =>  "IMPHAL WEST", ],
            [ "state" => "Manipur",                     "name"  =>  "JIRIBAM", ],
            [ "state" => "Manipur",                     "name"  =>  "KAKCHING", ],
            [ "state" => "Manipur",                     "name"  =>  "KAMJONG", ],
            [ "state" => "Manipur",                     "name"  =>  "KANGPOKPI", ],
            [ "state" => "Manipur",                     "name"  =>  "NONEY", ],
            [ "state" => "Manipur",                     "name"  =>  "PHERZAWL", ],
            [ "state" => "Manipur",                     "name"  =>  "SENAPATI", ],
            [ "state" => "Manipur",                     "name"  =>  "TAMENGLONG", ],
            [ "state" => "Manipur",                     "name"  =>  "TENGNOUPAL", ],
            [ "state" => "Manipur",                     "name"  =>  "THOUBAL", ],
            [ "state" => "Manipur",                     "name"  =>  "UKHRUL", ],
            [ "state" => "Meghalaya",                   "name"  =>  "EASTERN WEST KHASI HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "EAST GARO HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "EAST JAINTIA HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "EAST KHASI HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "NORTH GARO HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "RI BHOI", ],
            [ "state" => "Meghalaya",                   "name"  =>  "SOUTH GARO HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "SOUTH WEST GARO HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "SOUTH WEST KHASI HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "WEST GARO HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "WEST JAINTIA HILLS", ],
            [ "state" => "Meghalaya",                   "name"  =>  "WEST KHASI HILLS", ],
            [ "state" => "Mizoram",                     "name"  =>  "AIZAWL", ],
            [ "state" => "Mizoram",                     "name"  =>  "CHAMPHAI", ],
            [ "state" => "Mizoram",                     "name"  =>  "Hnahthial", ],
            [ "state" => "Mizoram",                     "name"  =>  "KHAWZAWL", ],
            [ "state" => "Mizoram",                     "name"  =>  "KOLASIB", ],
            [ "state" => "Mizoram",                     "name"  =>  "LAWNGTLAI", ],
            [ "state" => "Mizoram",                     "name"  =>  "LUNGLEI", ],
            [ "state" => "Mizoram",                     "name"  =>  "MAMIT", ],
            [ "state" => "Mizoram",                     "name"  =>  "SAIHA", ],
            [ "state" => "Mizoram",                     "name"  =>  "SAITUAL", ],
            [ "state" => "Mizoram",                     "name"  =>  "SERCHHIP", ],
            [ "state" => "Nagaland",                    "name"  =>  "Chumoukedima", ],
            [ "state" => "Nagaland",                    "name"  =>  "DIMAPUR", ],
            [ "state" => "Nagaland",                    "name"  =>  "KIPHIRE", ],
            [ "state" => "Nagaland",                    "name"  =>  "KOHIMA", ],
            [ "state" => "Nagaland",                    "name"  =>  "LONGLENG", ],
            [ "state" => "Nagaland",                    "name"  =>  "MOKOKCHUNG", ],
            [ "state" => "Nagaland",                    "name"  =>  "MON", ],
            [ "state" => "Nagaland",                    "name"  =>  "Noklak", ],
            [ "state" => "Nagaland",                    "name"  =>  "PEREN", ],
            [ "state" => "Nagaland",                    "name"  =>  "PHEK", ],
            [ "state" => "Nagaland",                    "name"  =>  "Tseminyu", ],
            [ "state" => "Nagaland",                    "name"  =>  "TUENSANG", ],
            [ "state" => "Nagaland",                    "name"  =>  "WOKHA", ],
            [ "state" => "Nagaland",                    "name"  =>  "ZUNHEBOTO", ],
            [ "state" => "Odisha",                      "name"  =>  "ANUGUL", ],
            [ "state" => "Odisha",                      "name"  =>  "BALANGIR", ],
            [ "state" => "Odisha",                      "name"  =>  "BALESHWAR", ],
            [ "state" => "Odisha",                      "name"  =>  "BARGARH", ],
            [ "state" => "Odisha",                      "name"  =>  "BHADRAK", ],
            [ "state" => "Odisha",                      "name"  =>  "BOUDH", ],
            [ "state" => "Odisha",                      "name"  =>  "CUTTACK", ],
            [ "state" => "Odisha",                      "name"  =>  "DEOGARH", ],
            [ "state" => "Odisha",                      "name"  =>  "DHENKANAL", ],
            [ "state" => "Odisha",                      "name"  =>  "GAJAPATI", ],
            [ "state" => "Odisha",                      "name"  =>  "GANJAM", ],
            [ "state" => "Odisha",                      "name"  =>  "JAGATSINGHAPUR", ],
            [ "state" => "Odisha",                      "name"  =>  "JAJAPUR", ],
            [ "state" => "Odisha",                      "name"  =>  "JHARSUGUDA", ],
            [ "state" => "Odisha",                      "name"  =>  "KALAHANDI", ],
            [ "state" => "Odisha",                      "name"  =>  "KANDHAMAL", ],
            [ "state" => "Odisha",                      "name"  =>  "KENDRAPARA", ],
            [ "state" => "Odisha",                      "name"  =>  "KENDUJHAR", ],
            [ "state" => "Odisha",                      "name"  =>  "KHORDHA", ],
            [ "state" => "Odisha",                      "name"  =>  "KORAPUT", ],
            [ "state" => "Odisha",                      "name"  =>  "MALKANGIRI", ],
            [ "state" => "Odisha",                      "name"  =>  "MAYURBHANJ", ],
            [ "state" => "Odisha",                      "name"  =>  "NABARANGPUR", ],
            [ "state" => "Odisha",                      "name"  =>  "NAYAGARH", ],
            [ "state" => "Odisha",                      "name"  =>  "NUAPADA", ],
            [ "state" => "Odisha",                      "name"  =>  "PURI", ],
            [ "state" => "Odisha",                      "name"  =>  "RAYAGADA", ],
            [ "state" => "Odisha",                      "name"  =>  "SAMBALPUR", ],
            [ "state" => "Odisha",                      "name"  =>  "SONEPUR", ],
            [ "state" => "Odisha",                      "name"  =>  "SUNDARGARH", ],
            [ "state" => "Puducherry",                  "name"  =>  "KARAIKAL", ],
            [ "state" => "Puducherry",                  "name"  =>  "MAHE", ],
            [ "state" => "Puducherry",                  "name"  =>  "PONDICHERRY", ],
            [ "state" => "Puducherry",                  "name"  =>  "YANAM", ],
            [ "state" => "Punjab",                      "name"  =>  "AMRITSAR", ],
            [ "state" => "Punjab",                      "name"  =>  "BARNALA", ],
            [ "state" => "Punjab",                      "name"  =>  "BATHINDA", ],
            [ "state" => "Punjab",                      "name"  =>  "FARIDKOT", ],
            [ "state" => "Punjab",                      "name"  =>  "FATEHGARH SAHIB", ],
            [ "state" => "Punjab",                      "name"  =>  "FAZILKA", ],
            [ "state" => "Punjab",                      "name"  =>  "FEROZEPUR", ],
            [ "state" => "Punjab",                      "name"  =>  "GURDASPUR", ],
            [ "state" => "Punjab",                      "name"  =>  "HOSHIARPUR", ],
            [ "state" => "Punjab",                      "name"  =>  "JALANDHAR", ],
            [ "state" => "Punjab",                      "name"  =>  "KAPURTHALA", ],
            [ "state" => "Punjab",                      "name"  =>  "LUDHIANA", ],
            [ "state" => "Punjab",                      "name"  =>  "MALERKOTLA", ],
            [ "state" => "Punjab",                      "name"  =>  "MANSA", ],
            [ "state" => "Punjab",                      "name"  =>  "MOGA", ],
            [ "state" => "Punjab",                      "name"  =>  "PATHANKOT", ],
            [ "state" => "Punjab",                      "name"  =>  "PATIALA", ],
            [ "state" => "Punjab",                      "name"  =>  "RUPNAGAR", ],
            [ "state" => "Punjab",                      "name"  =>  "SANGRUR", ],
            [ "state" => "Punjab",                      "name"  =>  "S.A.S Nagar", ],
            [ "state" => "Punjab",                      "name"  =>  "Shahid Bhagat Singh Nagar", ],
            [ "state" => "Punjab",                      "name"  =>  "SRI MUKTSAR SAHIB", ],
            [ "state" => "Punjab",                      "name"  =>  "Tarn Taran", ],
            [ "state" => "Rajasthan",                   "name"  =>  "AJMER", ],
            [ "state" => "Rajasthan",                   "name"  =>  "ALWAR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "BANSWARA", ],
            [ "state" => "Rajasthan",                   "name"  =>  "BARAN", ],
            [ "state" => "Rajasthan",                   "name"  =>  "BARMER", ],
            [ "state" => "Rajasthan",                   "name"  =>  "BHARATPUR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "BHILWARA", ],
            [ "state" => "Rajasthan",                   "name"  =>  "BIKANER", ],
            [ "state" => "Rajasthan",                   "name"  =>  "BUNDI", ],
            [ "state" => "Rajasthan",                   "name"  =>  "CHITTORGARH", ],
            [ "state" => "Rajasthan",                   "name"  =>  "CHURU", ],
            [ "state" => "Rajasthan",                   "name"  =>  "DAUSA", ],
            [ "state" => "Rajasthan",                   "name"  =>  "DHOLPUR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "DUNGARPUR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "GANGANAGAR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "HANUMANGARH", ],
            [ "state" => "Rajasthan",                   "name"  =>  "JAIPUR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "JAISALMER", ],
            [ "state" => "Rajasthan",                   "name"  =>  "JALORE", ],
            [ "state" => "Rajasthan",                   "name"  =>  "JHALAWAR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "JHUNJHUNU", ],
            [ "state" => "Rajasthan",                   "name"  =>  "JODHPUR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "KARAULI", ],
            [ "state" => "Rajasthan",                   "name"  =>  "KOTA", ],
            [ "state" => "Rajasthan",                   "name"  =>  "NAGAUR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "PALI", ],
            [ "state" => "Rajasthan",                   "name"  =>  "PRATAPGARH", ],
            [ "state" => "Rajasthan",                   "name"  =>  "RAJSAMAND", ],
            [ "state" => "Rajasthan",                   "name"  =>  "SAWAI MADHOPUR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "SIKAR", ],
            [ "state" => "Rajasthan",                   "name"  =>  "SIROHI", ],
            [ "state" => "Rajasthan",                   "name"  =>  "TONK", ],
            [ "state" => "Rajasthan",                   "name"  =>  "UDAIPUR", ],
            [ "state" => "Sikkim",                      "name"  =>  "Gangtok", ],
            [ "state" => "Sikkim",                      "name"  =>  "Gyalshing", ],
            [ "state" => "Sikkim",                      "name"  =>  "Mangan", ],
            [ "state" => "Sikkim",                      "name"  =>  "Namchi", ],
            [ "state" => "Sikkim",                      "name"  =>  "Pakyong", ],
            [ "state" => "Sikkim",                      "name"  =>  "Soreng", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "Ariyalur", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "CHENGALPATTU", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "CHENNAI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "COIMBATORE", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "CUDDALORE", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "DHARMAPURI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "DINDIGUL", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "ERODE", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "KALLAKURICHI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "KANCHIPURAM", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "KANNIYAKUMARI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "KARUR", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "KRISHNAGIRI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "MADURAI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "Mayiladuthurai", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "NAGAPATTINAM", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "NAMAKKAL", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "PERAMBALUR", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "PUDUKKOTTAI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "RAMANATHAPURAM", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "Ranipet", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "SALEM", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "SIVAGANGA", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "TENKASI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "THANJAVUR", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "THENI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "THE NILGIRIS", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "THIRUVALLUR", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "THIRUVARUR", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "TIRUCHIRAPPALLI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "TIRUNELVELI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "Tirupathur", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "TIRUPPUR", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "TIRUVANNAMALAI", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "TUTICORIN", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "VELLORE", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "VILLUPURAM", ],
            [ "state" => "Tamil Nadu",                 "name"  =>  "VIRUDHUNAGAR", ],
            [ "state" => "Telangana",                   "name"  =>  "ADILABAD", ],
            [ "state" => "Telangana",                   "name"  =>  "BHADRADRI KOTHAGUDEM", ],
            [ "state" => "Telangana",                   "name"  =>  "HANUMAKONDA", ],
            [ "state" => "Telangana",                   "name"  =>  "HYDERABAD", ],
            [ "state" => "Telangana",                   "name"  =>  "Jagitial", ],
            [ "state" => "Telangana",                   "name"  =>  "JANGOAN", ],
            [ "state" => "Telangana",                   "name"  =>  "JAYASHANKAR BHUPALAPALLY", ],
            [ "state" => "Telangana",                   "name"  =>  "JOGULAMBA GADWAL", ],
            [ "state" => "Telangana",                   "name"  =>  "KAMAREDDY", ],
            [ "state" => "Telangana",                   "name"  =>  "KARIMNAGAR", ],
            [ "state" => "Telangana",                   "name"  =>  "KHAMMAM", ],
            [ "state" => "Telangana",                   "name"  =>  "KUMURAM BHEEM ASIFABAD", ],
            [ "state" => "Telangana",                   "name"  =>  "MAHABUBABAD", ],
            [ "state" => "Telangana",                   "name"  =>  "MAHABUBNAGAR", ],
            [ "state" => "Telangana",                   "name"  =>  "MANCHERIAL", ],
            [ "state" => "Telangana",                   "name"  =>  "MEDAK", ],
            [ "state" => "Telangana",                   "name"  =>  "MEDCHAL MALKAJGIRI", ],
            [ "state" => "Telangana",                   "name"  =>  "Mulugu", ],
            [ "state" => "Telangana",                   "name"  =>  "NAGARKURNOOL", ],
            [ "state" => "Telangana",                   "name"  =>  "NALGONDA", ],
            [ "state" => "Telangana",                   "name"  =>  "Narayanpet", ],
            [ "state" => "Telangana",                   "name"  =>  "Nirmal", ],
            [ "state" => "Telangana",                   "name"  =>  "NIZAMABAD", ],
            [ "state" => "Telangana",                   "name"  =>  "PEDDAPALLI", ],
            [ "state" => "Telangana",                   "name"  =>  "RAJANNA SIRCILLA", ],
            [ "state" => "Telangana",                   "name"  =>  "RANGA REDDY", ],
            [ "state" => "Telangana",                   "name"  =>  "SANGAREDDY", ],
            [ "state" => "Telangana",                   "name"  =>  "SIDDIPET", ],
            [ "state" => "Telangana",                   "name"  =>  "SURYAPET", ],
            [ "state" => "Telangana",                   "name"  =>  "VIKARABAD", ],
            [ "state" => "Telangana",                   "name"  =>  "WANAPARTHY", ],
            [ "state" => "Telangana",                   "name"  =>  "WARANGAL", ],
            [ "state" => "Telangana",                   "name"  =>  "YADADRI BHUVANAGIRI", ],
            [ "state" => "The Dadra and Nagar Haveli and Daman and Diu","name" =>"DADRA AND NAGAR HAVELI", ],
            [ "state" => "The Dadra and Nagar Haveli and Daman and Diu","name" => "DAMAN", ],
            [ "state" => "The Dadra and Nagar Haveli and Daman and Diu","name" => "DIU", ],
            [ "state" => "Tripura",                   "name"  => "Dhalai", ],
            [ "state" => "Tripura",                   "name"  => "Gomati", ],
            [ "state" => "Tripura",                   "name"  => "Khowai", ],
            [ "state" => "Tripura",                   "name"  => "North Tripura", ],
            [ "state" => "Tripura",                   "name"  => "Sepahijala", ],
            [ "state" => "Tripura",                   "name"  => "South Tripura", ],
            [ "state" => "Tripura",                   "name"  => "Unakoti", ],
            [ "state" => "Tripura",                   "name"  => "West Tripura", ],
            [ "state" => "Uttarakhand",               "name"  =>  "ALMORA", ],
            [ "state" => "Uttarakhand",               "name"  =>  "BAGESHWAR", ],
            [ "state" => "Uttarakhand",               "name"  =>  "CHAMOLI", ],
            [ "state" => "Uttarakhand",               "name"  =>  "CHAMPAWAT", ],
            [ "state" => "Uttarakhand",               "name"  =>  "DEHRADUN", ],
            [ "state" => "Uttarakhand",               "name"  =>  "HARIDWAR", ],
            [ "state" => "Uttarakhand",               "name"  =>  "NAINITAL", ],
            [ "state" => "Uttarakhand",               "name"  =>  "PAURI GARHWAL", ],
            [ "state" => "Uttarakhand",               "name"  =>  "PITHORAGARH", ],
            [ "state" => "Uttarakhand",               "name"  =>  "RUDRA PRAYAG", ],
            [ "state" => "Uttarakhand",               "name"  =>  "TEHRI GARHWAL", ],
            [ "state" => "Uttarakhand",               "name"  =>  "UDAM SINGH NAGAR", ],
            [ "state" => "Uttarakhand",               "name"  =>  "UTTAR KASHI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "AGRA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "ALIGARH", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "AMBEDKAR NAGAR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "Amethi", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "AMROHA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "AURAIYA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "AYODHYA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "AZAMGARH", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BAGHPAT", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BAHRAICH", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BALLIA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BALRAMPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BANDA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BARABANKI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BAREILLY", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BASTI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BHADOHI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BIJNOR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BUDAUN", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "BULANDSHAHR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "CHANDAULI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "CHITRAKOOT", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "DEORIA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "ETAH", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "ETAWAH", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "FARRUKHABAD", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "FATEHPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "FIROZABAD", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "GAUTAM BUDDHA NAGAR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "GHAZIABAD", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "GHAZIPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "GONDA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "GORAKHPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "HAMIRPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "HAPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "HARDOI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "HATHRAS", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "JALAUN", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "JAUNPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "JHANSI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "KANNAUJ", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "KANPUR DEHAT", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "KANPUR NAGAR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "Kasganj", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "KAUSHAMBI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "KHERI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "KUSHI NAGAR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "LALITPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "LUCKNOW", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MAHARAJGANJ", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MAHOBA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MAINPURI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MATHURA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MAU", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MEERUT", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MIRZAPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MORADABAD", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "MUZAFFARNAGAR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "PILIBHIT", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "PRATAPGARH", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "PRAYAGRAJ", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "RAE BARELI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "RAMPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SAHARANPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SAMBHAL", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SANT KABEER NAGAR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SHAHJAHANPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SHAMLI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SHRAVASTI", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SIDDHARTH NAGAR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SITAPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SONBHADRA", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "SULTANPUR", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "UNNAO", ],
            [ "state" => "Uttar Pradesh",             "name"  =>  "VARANASI", ],
            [ "state" => "West Bengal",               "name"  => "24 PARAGANAS NORTH", ],
            [ "state" => "West Bengal",               "name"  => "24 PARAGANAS SOUTH", ],
            [ "state" => "West Bengal",               "name"  => "Alipurduar", ],
            [ "state" => "West Bengal",               "name"  => "BANKURA", ],
            [ "state" => "West Bengal",               "name"  => "BIRBHUM", ],
            [ "state" => "West Bengal",               "name"  => "COOCHBEHAR", ],
            [ "state" => "West Bengal",               "name"  => "DARJEELING", ],
            [ "state" => "West Bengal",               "name"  => "DINAJPUR DAKSHIN", ],
            [ "state" => "West Bengal",               "name"  => "DINAJPUR UTTAR", ],
            [ "state" => "West Bengal",               "name"  => "HOOGHLY", ],
            [ "state" => "West Bengal",               "name"  => "HOWRAH", ],
            [ "state" => "West Bengal",               "name"  => "JALPAIGURI", ],
            [ "state" => "West Bengal",               "name"  => "Jhargram", ],
            [ "state" => "West Bengal",               "name"  => "KALIMPONG", ],
            [ "state" => "West Bengal",               "name"  => "KOLKATA", ],
            [ "state" => "West Bengal",               "name"  => "MALDAH", ],
            [ "state" => "West Bengal",               "name"  => "MEDINIPUR EAST", ],
            [ "state" => "West Bengal",               "name"  => "MEDINIPUR WEST", ],
            [ "state" => "West Bengal",               "name"  => "MURSHIDABAD", ],
            [ "state" => "West Bengal",               "name"  => "NADIA", ],
            [ "state" => "West Bengal",               "name"  => "PASCHIM BARDHAMAN", ],
            [ "state" => "West Bengal",               "name"  => "PURBA BARDHAMAN", ],
            [ "state" => "West Bengal",               "name"  => "PURULIA", ],
        ];

        foreach($districts as $district)
        {
            $state = State::where("name", $district["state"])->first();
            if($state)
            {
                District::firstOrCreate([
                    "state_id" => $state->id,
                    "name" => $district["name"],
                ]);
            }
        }
    }
}
